language: java
jdk:
  - oraclejdk7
  - openjdk7
 
before_install:
 - chmod +x gradlew
 
install: true
script: 
  - ./gradlew -i test
after_success:
  - ./gradlew coveralls
    
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock    
    
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/